name: assistsaude
description: Evoluindo com Você.

publish_to: 'none'

version: 2.0.0+1

environment:
  
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  geolocator: ^9.0.2
  get: null
  get_storage: null
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.0.11
  http: ^0.13.4
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  local_auth: ^2.1.2
  mask_text_input_formatter: ^2.1.0
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.4
  table_calendar: ^3.0.2
  shared_preferences: ^2.0.8
  onesignal_flutter: ^3.4.1
  intl: ^0.17.0
  transparent_image: ^2.0.0
  cached_network_marker: ^0.1.1
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.1.6

  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/