name: assistsaude
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.3
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
